### PR TITLE
Attempt to fix issue #341

### PR DESCRIPTION
**Pull request by jriley-dhsc**
As per https://github.com/pierucci/heemod/issues/341 the message when look_up encounters missing values makes a bit more sense.

I've not done many PRs on other people's projects, so let me know if I've done anything wrong.

I'm not _sure_ if I've introduced new dependencies for the project, if so then I can rewrite some bits.

### CODE REVIEW

**Comment by KZARCA** [comment]
Hi! 
Thank you!
Dependencies of heemod are :
   dplyr
    ggplot2
    lazyeval
    memoise
    mvnfast 
    plyr 
    pry
    tibble
    rlang
Could you please add a test and update the NEWS file?
Best

**Comment by jriley-dhsc** [comment]
Is that hitting "build package" in Rstudio, and updating news.md? Apologies, I'm not very familiar with pacakge development.

**Comment by KZARCA** [comment]
Thanks, I slightly modified your code and added tests. Best

**Comment by jriley-dhsc** [comment]
Thank you very much!

**Pull request closed without merging**
