### PR TITLE
Daniels4321 efficiencey frontier

### PR DESCRIPTION
**Pull request by daniels4321**
Changes to get_efficiency_frontier to 
--handle special case of all but one strategy on the frontier (all others are dominated)
--throw error when only one strategy is provided
Changes to test_efficiency_frontier.R to challenge above special cases

### CODE REVIEW

**Comment by daniels4321** [comment]
Antoine,  this pull has additional changes to test_efficiency_frontier.R for several edge cases.  In particular, the case when all strategies are dominated by one strategy.  It also has a different implementation of the the get_frontier method which you probably don't want since you have the iterative method functioning for most cases.  should I close this pull request and submit another with only the test file changes?  Or do you just want add the new tests yourself?

**Comment by pierucci** [comment]
I'll have a look at your implementation, if it covers more cases than the current function then it's probably better to choose your solution. I'll pick the changes myself in your pull request, no need to do a new one.

A question: why do you want the function to throw an error when only one strategy is provided?

**Comment by daniels4321** [comment]
to ask for the efficient frontier for a single strategy could be considered meaningless.  for example, there's no way to calculate an icer for one strategy and the icers are part of the definition of the frontier.  On the other-hand, you could also argue it is simply degenerate and return always return the single strategy as the frontier, you just won't have any icers.  On further consideration, the later is probably the most consistent way to handle it.

**Comment by pierucci** [comment]
I added your tests and updated the code to manage some edge cases in bbc1abfbbfb9a1e2e35d1c239d4e79ed0812e050. Thanks a lot for your thorough debugging!

**Pull request closed without merging**
