### PR TITLE
some changes, mostly to survival modifications

### PR DESCRIPTION
**Pull request by MattWiener**
This still has the problem with not being able to see "survival_fits_from_ref_struc".   I will look at a way to include a small version in this version so at least fits can be loaded, though not fit.

### CODE REVIEW

**Comment by MattWiener** [comment]
The new changes (on April 28) are mostly a refactoring of part_surv.R, with some additions to tabular_input.R, so that people can use explicitly declared distributions or load existing fit files even if they do not have the survival fitting pieces (which are in my code, but so far not included in the main package).

**Comment by pierucci** [comment]
Oops sorry did not mean to close it. You can re-open the PR. (I can't on my side)

**Comment by MattWiener** [comment]
seeing whether this will bring it back

**Comment by MattWiener** [comment]
I cannot reopen either.   I think if you comment again the "reopen" button may reappear.   Otherwise, I will have to try to open a new pull request.

**Comment by pierucci** [comment]
I just had to re-create the branch...

**Comment by MattWiener** [comment]
closing because I'm about to replace

**Pull request closed without merging**
